// Tailwind SSR safelist.
// These literal strings are scanned by Tailwind v4 so CSS for SSR-only
// classes emitted by the API markdown renderer is generated at build time.

export const SSR_TAILWIND_SAFELIST = [
	'lg:bg-shell lg:rounded-2xl lg:shadow-[0_0_8px_-1px] lg:shadow-foreground/35 p-4 lg:p-6 w-full grid grid-flow-row grid-cols-1 auto-rows-[minmax(5vh,auto)] items-center gap-4 lg:gap-5',
	'md:px-5 lg:px-19 grid auto-cols-fr auto-rows-subgrid grid-flow-dense items-center lg:gap-9 gap-6.5',
	'*:leading-relaxed px-4',
	'flex flex-col items-start justify-center text-left rounded-2xl p-5 gap-3 border-l-6 shadow-md [&>math]:text-2xl! col-span-full w-full',
	'border-box-intro bg-box-intro-bg',
	'border-box-step bg-box-step-bg',
	'border-box-theory bg-box-theory-bg',
	'border-box-alert bg-box-alert-bg',
	'border-box-result bg-box-result-bg',
	'pt-0 pb-3',
	'w-full grid grid-cols-1 auto-rows-fr gap-1.5 grid-flow-row mt-7',
	'grid-rows-1 auto-cols-fr grid-flow-col grid grid-cols-2 items-center w-full px-6 text-center',
	'grid-rows-1 auto-cols-fr grid-flow-col grid grid-cols-1 items-center w-full px-6 text-center',
	'col-span-1',
	'text-2xl lg:text-3xl font-black text-black',
	'text-xl lg:text-2xl font-bold leading-normal flex flex-row items-center justify-start gap-x-1.5 lg:gap-x-5',
	'size-2.5 bg-brand rounded-full mb-1 -ml-0.5 mask-[radial-gradient(closest-side,black_30%,transparent_70%)]',
	'text-xl font-semibold italic leading-normal',
	'text-xl font-bold italic leading-none!',
	'opacity-75 leading-normal inline m-0 text-left',
	'font-bold text-black',
	'w-full h-auto',
	'border-t border-gray-300 w-full mask-[radial-gradient(closest-side,black_30%,transparent_70%)] my-4',
	'border-t border-gray-300 w-full mask-[radial-gradient(closest-side,black_30%,transparent_70%)] mt-4',
	'border-l border-gray-300 h-full mask-[radial-gradient(closest-side,black_30%,transparent_70%)]',
	'text-base [&:where(#box_*)]:text-lg text-katex font-bold inline-block contrast-110 opacity-100! drop-shadow-foreground/65 mx-auto dark:w-4 leading-none *:contents *:m-0!',
	'text-xl',
	'relative text-lg font-bold inline-block contrast-110 opacity-100! drop-shadow-foreground/65 text-katex',
	'sr-only',
	'inline m-0 text-left text-lg mx-auto px-4 py-1 text-white rounded-l-full rounded-r-full bg-[#004890] opacity-100',
	'inline m-0 text-left text-base mx-auto px-4 py-1 text-black rounded-l-full rounded-r-full bg-[#FFB703] opacity-100',
	'inline m-0 text-left text-base mx-auto px-4 py-1 text-white rounded-l-full rounded-r-full bg-[#06D6A0] opacity-100',
	'sticky top-p z-50 row-span-1 col-span-full shrink-0 h-fit flex flex-row items-center w-full max-w-maxwidth',
	'font-logo text-6xl mx-auto rounded-full backdrop-blur-lg border border-white/65 bg-white/30 px-6 pt-2 pb-3 leading-7 shadow-black/35 shadow-[0_0_8px_-1px]',
	'flex flex-col md:flex-row lg:items-start justify-between w-full',
	'py-1.5',
	'max-md:sr-only mt-auto lg:my-auto rounded-2xl object-cover h-full w-auto max-w-[30%] max-h-42',
	'flex flex-col items-center max-w-maxwidth w-full gap-[calc(3*var(--p))] pb-4',
	'bg-slate-50 text-slate-600 border-t-2 border-[#115eeb] w-full bottom-0 left-0',
	'max-w-5xl mx-auto px-4 py-10 flex flex-col md:flex-row md:justify-between gap-8 text-center md:text-left',
	'md:w-1/3 flex flex-col items-center md:items-start',
	'text-lg text-[#115eeb]',
	'text-sm mt-1',
	'flex flex-col gap-2',
	'font-semibold mb-1',
	'hover:underline',
	'border-t border-brand text-xs text-center py-4 px-2 bg-slate-50',
	'text-[11px] text-slate-500 max-w-2xl mx-auto',
] as const;

export default SSR_TAILWIND_SAFELIST;
